CREATE SCHEMA IF NOT EXISTS `parking` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci;
USE `parking`;
CREATE TABLE IF NOT EXISTS `all_parking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `town` VARCHAR(50) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `places` VARCHAR(6) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;